---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbi
  template:
    metadata:
      labels:
        app: gbi
    spec:
      containers:
      - name: gbi
        image: vickytg1/gbi:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gbi
spec:
  selector:
    app: gbi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
