name: Build,Analyze,scan
on:
  push:
    branches:
      - main
jobs:
  build-analyze-scan:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build and analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
      - name: npm install dependency
        run: npm install

      - name: Trivy file scan
        run: trivy fs . >trivyfs.txt

      - name: Docker Build and push
        run: |
          docker build -t gbi .
          docker tag gbi vickytg1/gbi:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push vickytg1/gbi:latest
        env:
          DOCKER_CLI_ACI: 1

      - name: Image scan
        run: trivy image vickytg1/gbi:latest

  deploy:
   needs: build-analyze-scan
   runs-on: [self-hosted]
   steps:
      - name: docker pull image
        run: docker pull vickytg1/gbi:latest
      - name: Image scan
        run: trivy image vickytg1/gbi:latest > trivyimagedeploy.txt
      - name: Deploy to container
        run: docker run -d --name game -p 80:80 vickytg1/gbi:latest
      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD
      - name: Deploy to kubernetes
        run: kubectl apply -f deployment-service.yml
          
